import './js/modal.js';
import './js/audio.js'
import './js/swiper.js'
import './js/gift-over.js'
import './js/reiki-swiper'
import './js/faq-accordion.js'
import './js/up-btn.js'
import './js/retreat-overlay.js'
import './js/lazy-loading.js'
