name: Deploy

on:
  push:
    branches: [main]

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - run: |
          cd dist
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "deploy"
          git push -f https://github.com/${{ github.repository }}.git gh-pages
